# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on 123
version: "1.2.0"
slug: example
description: Example add-on 123
url: "https://github.com/Sherd21/ha-addon-test/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  - message: "Hello world...123"
  - opt1: "opt1 value"
  - opt2: "opt2 value"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
